name: unhinged_date
description: "A clean/sober dating app that works."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0

  # State, routing
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0

  # Auth providers
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1

  # Device/services
  geolocator: ^11.1.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.4.0

  # UI/data utils
  cached_network_image: ^3.4.1
  crypto: ^3.0.3
  intl: ^0.20.2
  uuid: ^4.5.1
  timeago: ^3.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
