// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'app_router.dart'; // has AppRouter.router

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await GoogleSignIn.instance.initialize();
  // PRODUCTION-ish setup
  await FirebaseAppCheck.instance.activate(
    androidProvider:
        AndroidProvider.playIntegrity, // requires SHA-256 + Play Integrity API
    appleProvider: AppleProvider
        .appAttestWithDeviceCheckFallback, // iOS 14+; falls back to DeviceCheck
    // For web, use your v3 site key (or Enterprise if you use that):
    // webProvider: ReCaptchaV3Provider('YOUR_RECAPTCHA_V3_SITE_KEY'),
  );
  runApp(const UnhingedApp());
}

class UnhingedApp extends StatelessWidget {
  const UnhingedApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Unhinged',
      // TODO: swap ThemeData() for your theme from theme.dart if you want.
      theme: ThemeData(
        colorSchemeSeed: const Color(0xFF6E59A5),
        useMaterial3: true,
      ),
      routerConfig:
          AppRouter.router, // <-- use the static router, not buildRouter()
    );
  }
}
