// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // generated by flutterfire configure
import 'app_router.dart'; // has AppRouter.router

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const UnhingedApp());
}

class UnhingedApp extends StatelessWidget {
  const UnhingedApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Unhinged',
      // TODO: swap ThemeData() for your theme from theme.dart if you want.
      theme: ThemeData(
        colorSchemeSeed: const Color(0xFF6E59A5),
        useMaterial3: true,
      ),
      routerConfig:
          AppRouter.router, // <-- use the static router, not buildRouter()
    );
  }
}
